CREATE SCHEMA cars;
CREATE DATABASE cars; /* SCHEMA and DATABASE are the same thing*/
USE cars;

/* Q.1 READ DATA*/

SELECT * FROM car_dekho;

/* Q.2 TOTAL CARS: TO GET A COUNT OF TOTAL RECORDS*/

SELECT COUNT(Name) FROM car_dekho;
SELECT COUNT(*) FROM car_dekho; /*WE CAN ALSO USE THIS QUERY AS IT WILL GIVE US THE SAME RESULT*/

/* Q.3 THE MANAGER ASKED THE EMPLOYEE, HOW MANY CARS WILL BE AVAILABLE IN 2023 ?*/

SELECT COUNT(Name) FROM car_dekho WHERE year="2023";
SELECT COUNT(*) FROM car_dekho WHERE year="2023"; /*WE CAN ALSO USE THIS QUERY AS IT WILL GIVE US THE SAME RESULT*/

/* Q.4 THE MANAGER ASKED THE EMPLOYEE , HOW MANY CARS IS AVAILABLE IN 2020, 2021, 2022 ?*/

SELECT COUNT(Name) FROM car_dekho 
WHERE year=2020
OR year=2021 
OR year=2022
GROUP BY year;

/* Q.5 THE CLIENT ASKED ME TO PRINT THE TOTAL OF ALL CARS BY YEAR. THE CLIENT DON'T WANT TO SEE ALL THE DETAILS*/

SELECT year,COUNT(Name) 
FROM car_dekho 
GROUP BY year ;

/* Q.6 THE CLIENT HAS ASKED THE CAR DEALER , HOW MANY DIESEL CARS ARE THERE IN 2020 ?*/

SELECT year , COUNT(NAME)
FROM car_dekho 
WHERE fuel="Diesel" 
AND year = 2020 
GROUP BY year;

SELECT year , COUNT(NAME)
FROM car_dekho 
WHERE fuel="Diesel" 
AND year = 2020 ;  /*WE CAN ALSO USE THIS QUERY AS IT WILL GIVE US THE SAME RESULT*/

/* Q.7 HOW MANY PETROL CARS ARE THERE IN 2020 ?*/

SELECT year, COUNT(Name)
FROM car_dekho
WHERE fuel="Petrol"
AND year = 2020;

/* Q.8 SHOW ALL THE CARS ACCORDING TO THE FUEL THEY HAVE AND GROUP BY YEAR */

SELECT year , COUNT(Name)
FROM car_dekho 
WHERE fuel = "Petrol"
GROUP BY year;

SELECT year , COUNT(Name)
FROM car_dekho 
WHERE fuel = "Diesel"
GROUP BY year;

SELECT year , COUNT(Name)
FROM car_dekho 
WHERE fuel = "Electric"
GROUP BY year;

SELECT year , COUNT(Name)
FROM car_dekho 
WHERE fuel = "CNG"
GROUP BY year;

/* Q.9 WHICH YEAR HAD MORE THAN 100 CARS ?*/

SELECT year, COUNT(Name) 
FROM car_dekho 
GROUP BY year 
HAVING COUNT(Name)>100; 

/* Q.10 ALL CARS BETWEEN 2015 AND 2023*/

SELECT  COUNT(name) 
FROM car_dekho
WHERE year BETWEEN 2015 AND 2023;

/*Q.11 ALL LIST OF CARS BETWEEN 2015 AND 2023*/

SELECT * FROM car_dekho WHERE year BETWEEN 2015 AND 2023;



